server:
  port: 8080
spring:
  profiles:
    active: xml
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmDemo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
  mvc:
    static-path-pattern: /static/**
    view:
      suffix: .html
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html